spring.application.name=producto-oas
server.port=8080

# Configuración del Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Conexión Dinámica: Se adapta automáticamente a local o a Railway
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:db_producto_stars}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:dada1234}

# Configuración de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Logs de Base de Datos (desactiva en producción si quieres)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.orm.jdbc.bind=warn

# Configuración del Entorno de Swagger
springdoc.swagger-ui.operationsSorter=method